### ISSUE TITLE
Use `Remotes` for pkgs on github and not on CRAN

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/snowball#1]
e.g., https://github.com/search?utf8=%E2%9C%93&q=filename%3ADESCRIPTION+path%3A%2F+Remotes&type=Code&ref=searchresults and the blog post https://blog.rstudio.org/2016/03/09/r-on-travis-ci/ 

Would allow `install_github` to automatically install those github pkgs when users install this pkg

**Comment by jonocarroll** [comment]
Thanks for this, brilliantly timed; I'm adding Travis CI to my repos at the moment (well, trying to) and was going to add it to this one too.

I was also unsure about how to get `install_github` to work automatically.

**Comment by jonocarroll** [comment]
I'll test the install later tonight and if successful, close this issue. Thanks again.
