### ISSUE TITLE
Transfer repo to a personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/snowball#2]
@jonocarroll et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by jonocarroll** [comment]
I'm happy to have this transferred to the ropensci-archive organisation. All authors are welcome to fork the project and develop independently. I do not think I will ever continue development myself.

**Comment by maelle** [comment]
Thank you!
